import = [
"~/.config/alacritty/colors.toml",
"~/.config/alacritty/keybindings.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"

[window.padding]
x = 16
y = 14

[cursor.style]
shape = "Beam"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 1
