import = [
"~/.config/alacritty/tokyonight_storm.toml",
"~/.config/alacritty/keybindings.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 18, y = 16 }
decorations = "Buttonless"
# option_as_alt = "Both"

[cursor]
style = { shape = "Beam" }

[font]
normal = { family = "FiraCode Nerd Font" }
size = 14
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }
