# TokyoNight Alacritty Colors (day)
# https://github.com/folke/tokyonight.nvim/blob/main/extras/alacritty/tokyonight_day.yml


# Default colors
[colors.primary]
background = '#e1e2e7'
foreground = '#3760bf'

# Normal colors
[colors.normal]
black    = '#e9e9ed'
red      = '#f52a65'
green    = '#587539'
yellow   = '#8c6c3e'
blue     = '#2e7de9'
magenta  = '#9854f1'
cyan     = '#007197'
white    = '#6172b0'

# Bright colors
[colors.bright]
black    = '#a1a6c5'
red      = '#f52a65'
green    = '#587539'
yellow   = '#8c6c3e'
blue     = '#2e7de9'
magenta  = '#9854f1'
cyan     = '#007197'
white    = '#3760bf'

[colors]
indexed_colors = [
{ index = 16, color = '0xb15c00' },
{ index = 17, color = '0xc64343' },
]
