return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	lazy = false,
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter").setup()

		-- Parsers To install (:TSInstall <language>)
		-- or pass to the install function: require("nvim-treesitter").install()
		-- "angular",
		-- "astro",
		-- "bash",
		-- "blade",
		-- "c",
		-- "comment",
		-- "css",
		-- "dockerfile",
		-- "gitcommit",
		-- "gitignore",
		-- "git_config",
		-- "html",
		-- "htmldjango",
		-- "javascript",
		-- "json",
		-- "lua",
		-- "markdown",
		-- "markdown_inline",
		-- "php",
		-- "python",
		-- "query",
		-- "toml",
		-- "tsx",
		-- "typescript",
		-- "sql",
		-- "vim",
		-- "vimdoc",
		-- "yaml",
	end,
}
